# Generated by Django 4.2.13 on 2024-05-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend_connect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendconnect',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
